### ISSUE TITLE
'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by masapasa** [duneanalytics/duneapi-client-python#3]
python duneapi.py 1105134
Traceback (most recent call last):
  File "duneapi-client-python/duneapi.py", line 106, in <module>
    rows = execute_query_and_get_results(query_id, api_key)
  File "duneapi-client-python/duneapi.py", line 81, in execute_query_and_get_results
    dune = DuneAPI(api_key)
  File "duneapi-client-python/duneapi.py", line 25, in __init__
    self.client = httpx.Client(headers=self.headers)
  File "anaconda3/envs/jina/lib/python3.9/site-packages/httpx/_client.py", line 647, in __init__
    super().__init__(
  File "anaconda3/envs/jina/lib/python3.9/site-packages/httpx/_client.py", line 179, in __init__
    self.headers = Headers(headers)
  File "anaconda3/envs/jina/lib/python3.9/site-packages/httpx/_models.py", line 69, in __init__
    self._list = [
  File "anaconda3/envs/jina/lib/python3.9/site-packages/httpx/_models.py", line 73, in <listcomp>
    normalize_header_value(v, encoding),
  File "anaconda3/envs/jina/lib/python3.9/site-packages/httpx/_utils.py", line 54, in normalize_header_value
    return value.encode(encoding or "ascii")
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by SusmeetJain** [comment]
Did you add your API key to your local environment before running this script?

   ```bash
   $ export DUNE_API_KEY="YOUR_API_KEY"
   ```
